import Vue from 'vue';
import { Collapse, CollapseItem, Toast, Icon, Dialog, NoticeBar, Button, Col, Row, NumberKeyboard,Overlay, Picker, Popup, Cell, CellGroup,DropdownMenu, DropdownItem ,Calendar,Search ,Field,List  ,ActionSheet  } from 'vant';
Vue.use(Dialog);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(Toast);
Vue.use(Icon);
Vue.use(NoticeBar);
Vue.use(Col);
Vue.use(Row);
Vue.use(Button);
Vue.use(NumberKeyboard);
Vue.use(Overlay);
Vue.use(Picker);
Vue.use(Popup);
Vue.use(Cell);
Vue.use(CellGroup);
Vue.use(DropdownMenu);
Vue.use(DropdownItem);
Vue.use(Calendar);
Vue.use(Search);
Vue.use(Field);
Vue.use(List);
Vue.use(ActionSheet);